### ISSUE TITLE
Failed to load the weather-package package

### ISSUE THREAD

**Issue by thibmaek** [gladimdim/weather-package#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [weather-package](https://github.com/gladimdim/weather-package) package, v1.5.1

### Stack Trace

Failed to load the weather-package package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/weather-package/lib/weather-package-view.coffee:4:199)
    at /Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/weather-package/lib/weather-package-view.coffee:11:5
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/weather-package/lib/weather-package-view.coffee:147:5)
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/weather-package/lib/weather-package-view.coffee:149:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/weather-package/lib/weather-package.coffee:4:24)
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/weather-package/lib/weather-package.coffee:21:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jslint",
      "emmet",
      "unregistered",
      "compass",
      "quippet",
      "autocomplete-paths",
      "autocomplete-plus"
    ],
    "themes": [
      "yeti-ui",
      "kimbie-light"
    ],
    "ignoredNames": [
      "node_modules",
      ".DS_Store",
      "npm-debug.log"
    ]
  },
  "weather-package": {
    "showInFahrenheit": false,
    "showTemperature": true,
    "showPressure": false,
    "city": "Bruges"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-bootstrap3, v1.2.0
atom-html-preview, v0.1.6
atom-spotify, v1.2.0
atom-terminal, v0.7.0
backbonejs-snippets, v0.4.1
close-tags, v0.2.0
compare-files, v0.4.1
editor-stats, v0.17.0
editorconfig, v0.3.3
error-status, v0.3.3
file-icons, v1.5.3
git-log, v0.3.0
git-plus, v4.4.12
gulp-helper, v2.0.0
gulp-snippets, v0.6.1
iTunes, v0.2.0
jsonlint, v1.0.2
kimbie-light, v1.0.1
language-swift, v0.3.0
laravel, v0.4.2
linter, v0.12.0
linter-flow, v0.1.4
linter-jshint, v0.1.1
linter-php, v0.0.12
linter-scss-lint, v0.0.14
open-in, v3.1.0
open-in-browser, v0.4.3
path, v0.4.1
remote-edit, v1.7.2
remote-sync, v2.4.1
ssh-config, v0.10.0
swift-playground, v0.2.0
travis-ci-status, v0.13.0
uglify, v1.2.0
weather-package, v1.5.1
web-browser, v1.4.3
yeti-ui, v0.1.6

# Dev
No dev packages
```

**Comment by gladimdim** [comment]
Hello @thibmaek ,

I have reinstalled this package from scratch and do not receive such exception. I have Atom 0.192.0 version installed. Could you please uninstall my package and try again? 

I have also released version 1.5.2 which fixes non-critical minor issues.

**Comment by thibmaek** [comment]
Seems to work now.
Sidenote: the colors look kinda hard in a light UI theme. Mind if I send a PR with better suiting colors for both light & dark UI's (I have been using it ever since I installed the package tbh)

![screen shot 2015-04-20 at 21 26 43](https://cloud.githubusercontent.com/assets/6213695/7238633/0c4f4baa-e7a4-11e4-9bf3-421fb47de81a.png)

**Comment by gladimdim** [comment]
@thibmaek Sure, please open whatever issue you want :) I will try to change colors.
